# Configuración adicional mínima. La base de datos y perfiles están en application.yml
spring.application.name=polleria-caporal
spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
